defaults: &defaults
  irc:
    channels: "<%= ENV['IRC_CHANNELS'] %>"
    nickname: "<%= ENV['IRC_NICKNAME'] %>"
    password: "<%= ENV['IRC_PASSWORD'] %>"
    port: <%= ENV.fetch('IRC_PORT', 6667).to_i %>
    prefix: "<%= ENV['IRC_PREFIX'] %>"
    realname: "<%= ENV['IRC_REALNAME'] %>"
    server: "<%= ENV['IRC_SERVER'] %>"
    ssl: <%= ENV['IRC_SSL'] == 'true' ? 'true' : 'false' %>
    username: "<%= ENV['IRC_USERNAME'] %>"

development:
  <<: *defaults

production:
  <<: *defaults

test:
  <<: *defaults
