defaults: &defaults
  blolol:
    api_key: "<%= ENV['BLOLOL_API_KEY'] %>"
    api_secret: "<%= ENV['BLOLOL_API_SECRET'] %>"
  game:
    base_xp_per_tick: <%= ENV.fetch('BASE_XP_PER_TICK', 4).to_i %>
    battle_probability_per_tick: <%= ENV.fetch('BATTLE_PROBABILITY', 1.0 / 60.0).to_f %>
    find_item_probability_per_tick: <%= ENV.fetch('FIND_ITEM_PROBABILITY', 1.0 / 60.0).to_f %>
    premium_xp_per_tick: <%= ENV.fetch('PREMIUM_XP_PER_TICK', 1).to_i %>
    seconds_between_ticks: <%= ENV.fetch('SECONDS_BETWEEN_TICKS', 60).to_i %>
  irc:
    channels: "<%= ENV['IRC_CHANNELS'] %>"
    nickname: "<%= ENV['IRC_NICKNAME'] %>"
    password: "<%= ENV['IRC_PASSWORD'] %>"
    port: <%= ENV.fetch('IRC_PORT', 6667).to_i %>
    prefix: "<%= ENV['IRC_PREFIX'] %>"
    realname: "<%= ENV['IRC_REALNAME'] %>"
    server: "<%= ENV['IRC_SERVER'] %>"
    ssl: <%= ENV['IRC_SSL'] == 'true' ? 'true' : 'false' %>
    username: "<%= ENV['IRC_USERNAME'] %>"

development:
  <<: *defaults

production:
  <<: *defaults

test:
  <<: *defaults
